Update README.md
The `present?` method is Rails-provided, so adding the pippi auto-runner code at the very top of a Rails `spec_helper.rb` file gives you an error:

```
... spec/spec_helper.rb:1:in '<top (required)>': undefined method `present?' for "true":String (NoMethodError)
```

Adding the code snippet below the `require 'rspec/rails` line does the trick.